AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-micronaut-sample
  Sample SAM Template for lambda-micronaut

Globals:
  Function:
    Tracing: Active
    CodeUri: build/libs/HandsOnOne-0.1-all.jar
    Runtime: java17
    Timeout: 30
    MemorySize: 1024
    Alarms:
      # All Lambda functions will get a Throttle CloudWatch alarm. If necessary, each function can override certain properties alarm as they need
      Throttles:
        Metric: "throttle"
        # Notify if the Lambda gets throttled in 5min interval
        Threshold: 1
        Timeframe: "5min"
        Notification:
          Type: Email
          Address: kilickoray1@gmail.com

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: feature
      Name: SM703 Hands-on-feature


  HelloWorldFunctionFeature:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Policies:
      Events:
        GetHelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: get

  HelloWorldFunctionLogGroupFeature:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HelloWorldFunctionFeature}"
      RetentionInDays: 7

Outputs:
  MicronautApiEndpoint:
    Description: "API Gateway endpoint URL for Feature stage for Micronaut sample function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/feature/"
