AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-micronaut-sample
  Sample SAM Template for lambda-micronaut

Globals:
  Function:
    Tracing: Active
    CodeUri: build/libs/HandsOnOne-0.1-all.jar
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: feature
      Name: SM703 Hands-on-feature
  ApiCount:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmDescription: 'My-Blah-api-v1 ApiGateway 4XXError'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub "${AWS::StackName}-api-v1"
      EvaluationPeriods: 1
      MetricName: Count
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:MyCompany_Cloudwatch_Alarms_Topic'


  HelloWorldFunctionFeature:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Policies:
      Events:
        GetHelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: get

  HelloWorldFunctionLogGroupFeature:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HelloWorldFunctionFeature}"
      RetentionInDays: 7

Outputs:
  MicronautApiEndpoint:
    Description: "API Gateway endpoint URL for Feature stage for Micronaut sample function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/feature/"
